CREATE DATABASE [cmapiDB] ON  PRIMARY 
( NAME = N'cmapiDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\cmapiDB.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'cmapiDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\cmapiDB_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [cmapiDB] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [cmapiDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [cmapiDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [cmapiDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [cmapiDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [cmapiDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [cmapiDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [cmapiDB] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [cmapiDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [cmapiDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [cmapiDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [cmapiDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [cmapiDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [cmapiDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [cmapiDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [cmapiDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [cmapiDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [cmapiDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [cmapiDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [cmapiDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [cmapiDB] SET  READ_WRITE 
GO
ALTER DATABASE [cmapiDB] SET RECOVERY FULL 
GO
ALTER DATABASE [cmapiDB] SET  MULTI_USER 
GO
ALTER DATABASE [cmapiDB] SET PAGE_VERIFY CHECKSUM  
GO
USE [cmapiDB]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [cmapiDB] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
